### ISSUE TITLE
WTF is going on? Every module is installed!+

### ISSUE THREAD

**Issue by eclipsek20** [aidanbxyz/kahoot-bot-spammer#1]
C:\Users\NYC\Desktop\katfu>node spamkahoot.js
node:internal/modules/cjs/loader:927
  throw err;
  ^

Error: Cannot find module './src/kahoot.js'
Require stack:
- C:\Users\NYC\node_modules\kahoot.js-updated\index.js
- C:\Users\NYC\Desktop\katfu\spamkahoot.js
←[90m    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:924:15)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:769:27)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:996:19)←[39m
←[90m    at require (node:internal/modules/cjs/helpers:92:18)←[39m
    at Object.<anonymous> (C:\Users\NYC\node_modules\←[4mkahoot.js-updated←[24m\index.js:1:16)
←[90m    at Module._compile (node:internal/modules/cjs/loader:1092:14)←[39m
←[90m    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)←[39m
←[90m    at Module.load (node:internal/modules/cjs/loader:972:32)←[39m
←[90m    at Function.Module._load (node:internal/modules/cjs/loader:813:14)←[39m
←[90m    at Module.require (node:internal/modules/cjs/loader:996:19)←[39m {
  code: ←[32m'MODULE_NOT_FOUND'←[39m,
  requireStack: [
    ←[32m'C:\\Users\\NYC\\node_modules\\kahoot.js-updated\\index.js'←[39m,
    ←[32m'C:\\Users\\NYC\\Desktop\\katfu\\spamkahoot.js'←[39m
  ]
}

**Comment by aidanbxyz** [comment]
Hello there! I just found out that kahoot.js-updated was deleted from npm on Feb 18, 2021. Luckily, I still have a way. Please re-clone the repo and rename the "node_modules.a" folder to "node_modules."
