### ISSUE TITLE
How to properly setup kahoot bot spammer on windows 

### ISSUE THREAD

**Issue by eclipsek20** [aidanbxyz/kahoot-bot-spammer#2]
1. You need to download and install node.js
2. You need to download this repo (or whatever they call it)
3. Once you have done that you have to extract the repo and copy the directory that you have extracted it in (For Example: C:/users/lol/desktop/kahoot-bot-spammer/)
4. Open command line and type in "cd (Directory to extracted repo)" for example "cd C:/users/lol/desktop/kahoot-bot-spammer/"
5. Once you have done that type in the following commands (each separately):
npm install random-useragent
npm install system-sleep
npm install got
npm install ws
6. Go to the extracted folder and copy the insides of the folder "node_modules.a" and paste it into the folder "node_modules"
7. It will ask you whether to overwrite the folder, agree to doing that.
8. Now open "spamkahoot.js" and enter the Kahoot id (or whatever they call it) and username
9. Now open command line again and type "cd (Location to Kahoot bot spammer)" for example "cd c:/users/lol/desktop/kahoot-bot-spammer"
10. The last thing to do is type "node spamkahoot.js"
11. If no error comes up you successfully followed my steps!

I think I will write a script that automates the process so stay tuned for that?

P.S. Please keep this issue open as i will update it. Sorry for my poor grammer.

**Comment by aidanbxyz** [comment]
I just added a script for windows and linux. It should work for most systems. Thanks for the detailed instructions.
